version: "3.8"

services:
  ecommerce:
    build:
      context: .
      dockerfile: apps/ecommerce/Dockerfile
    container_name: ecommerce
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  checkout:
    build:
      context: .
      dockerfile: apps/checkout/Dockerfile
    container_name: checkout
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
    depends_on:
      - ecommerce
      - checkout
    restart: always
