services:
  ecommerce:
    build:
      context: .
      dockerfile: apps/ecommerce/Dockerfile
    container_name: ecommerce
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

  checkout:
    build:
      context: .
      dockerfile: apps/checkout/Dockerfile
    container_name: checkout
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ecommerce
      - checkout
