name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy files to Droplet via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: deploy
          key: ${{ secrets.DO_SSH_KEY }}
          source: "."
          target: "/home/deploy/ecommerce-mfe"

      - name: SSH into server and deploy with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: deploy
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e
            cd /home/deploy/ecommerce-mfe

            echo "✅ Atualizando código"
            git pull origin develop || true

            echo "🛑 Parando containers antigos"
            docker compose down --remove-orphans

            echo "🚀 Subindo containers atualizados"
            docker compose up -d --build

            echo "✅ Deploy finalizado com sucesso"
